/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package padroes_de_projeto;

import main.java.padroes_de_projeto.factories.MongoDBFactory;
import main.java.padroes_de_projeto.factories.iDatabaseFactory;
import main.java.padroes_de_projeto.models.Aluno;

public class App {
    public static void main(String[] args) {
        iDatabaseFactory databaseFactory = new MongoDBFactory();
        Aluno aluno = new Aluno(databaseFactory);
        System.out.println(
            aluno.course.nomeCurso()
        );
    }
}
